server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange-3
    queue1: user.queue-1-2
    queue2: user.queue-2-2